#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set_default --key=admin --value=$(ynh_user_get_info --username=$admin --key=username)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#WIP : hopefully we can do this in a near future
#ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template="config-sample.php" --destination="$install_dir/src/config/config.php"

#=================================================
# PROVISION DATABASE
#=================================================
#ynh_script_progression "Provisionning database..."

#ynh_config_add --template="schema_mysql.sql" --destination="$install_dir/src/config/mysql.sql"

#ynh_mysql_db_shell < $install_dir/src/sql/mysql.sql

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
